version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: me
    container_name: me
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
    ports:
      - "5173:5173"
    networks:
      - app-network
    command: sh -c "cd /var/www && \ if [ ! -f .env ]; then cp .env.example .env && php artisan key:generate && echo 'APP_ID=EXAMPLE_APP_ID' >> .env; fi && \ if [ ! -d vendor ]; then composer install; fi && \ php-fpm"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mix:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev -- --host --port=5174"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

volumes:
  vendor:


networks:
  app-network:
    driver: bridge
