version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: me
    container_name: me
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  vite:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

volumes:
  vendor:

networks:
  app-network:
    driver: bridge
