version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    image: me
    container_name: me
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mix:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev -- --host --port=5174"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-service
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - ./:/var/www # Make sure your project files are available in the container
    ports:
      - "27017:27017"
    networks:
      - app-network
    command: /bin/bash -c "/var/www/import-json.sh"

volumes:
  vendor:
  mongodb_data:

networks:
  app-network:
    driver: bridge