version: '3'
services:
  app:
    image: me
    container_name: me
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      # Using local codebase but installing dependencies in the container
    ports:
      - "5173:5173"
    networks:
      - app-network
    # Run composer install for local development and ensure APP_KEY is generated
    command: sh -c "cd /var/www && if [ ! -f .env ]; then cp .env.example .env; fi && composer install && php artisan key:generate --force && php-fpm"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  mix:
    image: node:16
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: sh -c "npm install && npm run dev -- --host --port=5174"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
