/**
 * Terminal Themes - Shared theme definitions
 * Used by ThemeCommand, Preferences, and Terminal components
 */

export const TERMINAL_THEMES = {
    'default': {
        name: 'Default (LinkOS Terminal)',
        description: 'Classic LinkOS Terminal.app colors',
        background: '#000000',
        foreground: '#e0e0e0',
        cursor: '#00ff00',
        cursorAccent: '#000000',
        selection: 'rgba(255, 255, 255, 0.3)',
        black: '#2e3436',
        red: '#ff5555',
        green: '#50fa7b',
        yellow: '#f1fa8c',
        blue: '#4d9ef7',
        magenta: '#ff79c6',
        cyan: '#8be9fd',
        white: '#e0e0e0',
        brightBlack: '#888888',
        brightRed: '#ff8888',
        brightGreen: '#88ffaa',
        brightYellow: '#ffffaa',
        brightBlue: '#88ccff',
        brightMagenta: '#ffaaff',
        brightCyan: '#aaffff',
        brightWhite: '#ffffff'
    },
    'alien': {
        name: 'ABDULMELINK*',
        description: 'Weyland-Yutani MU/TH/UR 6000 System',
        background: '#000000',
        foreground: '#39ff14',
        cursor: '#39ff14',
        cursorAccent: '#000000',
        selection: 'rgba(57, 255, 20, 0.2)',
        black: '#000000',
        red: '#ff3b30',
        green: '#39ff14',
        yellow: '#ffcc00',
        blue: '#00a6ff',
        magenta: '#ff2d55',
        cyan: '#00ffcc',
        white: '#8fbc8f',
        brightBlack: '#1a4d1a',
        brightRed: '#ff6961',
        brightGreen: '#6bff4d',
        brightYellow: '#ffeb3b',
        brightBlue: '#4fc3f7',
        brightMagenta: '#ff80ab',
        brightCyan: '#64ffda',
        brightWhite: '#adff2f',
        sound: 'alien'
    },
    'matrix': {
        name: 'The Matrix',
        description: 'Digital rain cascading code',
        background: '#000000',
        foreground: '#00ff41',
        cursor: '#00ff41',
        cursorAccent: '#000000',
        selection: 'rgba(0, 255, 65, 0.3)',
        black: '#000000',
        red: '#ff073a',
        green: '#00ff41',
        yellow: '#fff113',
        blue: '#0066ff',
        magenta: '#ff00ff',
        cyan: '#00ffff',
        white: '#ffffff',
        brightBlack: '#555555',
        brightRed: '#ff6c60',
        brightGreen: '#a8ff60',
        brightYellow: '#ffffb6',
        brightBlue: '#96cbfe',
        brightMagenta: '#ff73fd',
        brightCyan: '#c6c5fe',
        brightWhite: '#ffffff'
    },
    'cyberpunk': {
        name: 'Cyberpunk 2077',
        description: 'Night City netrunner interface',
        background: '#0a0014',
        foreground: '#ff006e',
        cursor: '#ff006e',
        cursorAccent: '#0a0014',
        selection: 'rgba(255, 0, 110, 0.3)',
        black: '#0a0014',
        red: '#ff006e',
        green: '#00ffaa',
        yellow: '#ffaa00',
        blue: '#00aaff',
        magenta: '#ff00ff',
        cyan: '#00ffff',
        white: '#ffffff',
        brightBlack: '#555555',
        brightRed: '#ff4499',
        brightGreen: '#44ffcc',
        brightYellow: '#ffcc44',
        brightBlue: '#44ccff',
        brightMagenta: '#ff44ff',
        brightCyan: '#44ffff',
        brightWhite: '#ffffff'
    },
    'retro': {
        name: 'Retro Amber',
        description: 'Vintage CRT monitor glow',
        background: '#1a0f00',
        foreground: '#ffb000',
        cursor: '#ffb000',
        cursorAccent: '#1a0f00',
        selection: 'rgba(255, 176, 0, 0.3)',
        black: '#1a0f00',
        red: '#ff8c00',
        green: '#ffb000',
        yellow: '#ffd700',
        blue: '#ff9f40',
        magenta: '#ff7f50',
        cyan: '#ffcc80',
        white: '#ffe4b5',
        brightBlack: '#8b4513',
        brightRed: '#ffa54f',
        brightGreen: '#ffc966',
        brightYellow: '#ffe87c',
        brightBlue: '#ffb766',
        brightMagenta: '#ff9966',
        brightCyan: '#ffd9a3',
        brightWhite: '#fffacd'
    },
    'apple-ii': {
        name: 'Apple II',
        description: 'Green phosphor screen nostalgia',
        background: '#0f380f',
        foreground: '#33ff33',
        cursor: '#33ff33',
        cursorAccent: '#0f380f',
        selection: 'rgba(51, 255, 51, 0.25)',
        black: '#0f380f',
        red: '#66ff66',
        green: '#33ff33',
        yellow: '#99ff99',
        blue: '#44ff44',
        magenta: '#77ff77',
        cyan: '#88ff88',
        white: '#ccffcc',
        brightBlack: '#226622',
        brightRed: '#77ff77',
        brightGreen: '#55ff55',
        brightYellow: '#aaffaa',
        brightBlue: '#66ff66',
        brightMagenta: '#88ff88',
        brightCyan: '#99ff99',
        brightWhite: '#eeffee'
    },
    'tron': {
        name: 'TRON Legacy',
        description: 'The Grid digital frontier',
        background: '#000408',
        foreground: '#6fc3df',
        cursor: '#6fc3df',
        cursorAccent: '#000408',
        selection: 'rgba(111, 195, 223, 0.3)',
        black: '#000408',
        red: '#ff410d',
        green: '#00e8c6',
        yellow: '#ffb300',
        blue: '#6fc3df',
        magenta: '#ae81ff',
        cyan: '#00e8ff',
        white: '#a4c5d9',
        brightBlack: '#1c2833',
        brightRed: '#ff6f4f',
        brightGreen: '#33ffd9',
        brightYellow: '#ffd633',
        brightBlue: '#8fd9f0',
        brightMagenta: '#c8a0ff',
        brightCyan: '#66f0ff',
        brightWhite: '#dceef7'
    },
    'hacker': {
        name: 'Black Hat',
        description: 'Underground IRC green on black',
        background: '#000000',
        foreground: '#00ff00',
        cursor: '#00ff00',
        cursorAccent: '#000000',
        selection: 'rgba(0, 255, 0, 0.25)',
        black: '#000000',
        red: '#ff0000',
        green: '#00ff00',
        yellow: '#ffff00',
        blue: '#0000ff',
        magenta: '#ff00ff',
        cyan: '#00ffff',
        white: '#ffffff',
        brightBlack: '#808080',
        brightRed: '#ff8080',
        brightGreen: '#80ff80',
        brightYellow: '#ffff80',
        brightBlue: '#8080ff',
        brightMagenta: '#ff80ff',
        brightCyan: '#80ffff',
        brightWhite: '#ffffff'
    },
    'dracula': {
        name: 'Dracula',
        description: 'Dark theme with purple accents',
        background: '#282a36',
        foreground: '#f8f8f2',
        cursor: '#f8f8f2',
        selection: 'rgba(68, 71, 90, 0.5)',
        black: '#21222c',
        red: '#ff5555',
        green: '#50fa7b',
        yellow: '#f1fa8c',
        blue: '#bd93f9',
        magenta: '#ff79c6',
        cyan: '#8be9fd',
        white: '#f8f8f2',
        brightBlack: '#6272a4',
        brightRed: '#ff6e6e',
        brightGreen: '#69ff94',
        brightYellow: '#ffffa5',
        brightBlue: '#d6acff',
        brightMagenta: '#ff92df',
        brightCyan: '#a4ffff',
        brightWhite: '#ffffff'
    },
    'monokai': {
        name: 'Monokai',
        description: 'Sublime Text classic',
        background: '#272822',
        foreground: '#f8f8f2',
        cursor: '#f8f8f0',
        selection: 'rgba(73, 72, 62, 0.8)',
        black: '#272822',
        red: '#f92672',
        green: '#a6e22e',
        yellow: '#f4bf75',
        blue: '#66d9ef',
        magenta: '#ae81ff',
        cyan: '#a1efe4',
        white: '#f8f8f2',
        brightBlack: '#75715e',
        brightRed: '#f92672',
        brightGreen: '#a6e22e',
        brightYellow: '#f4bf75',
        brightBlue: '#66d9ef',
        brightMagenta: '#ae81ff',
        brightCyan: '#a1efe4',
        brightWhite: '#f9f8f5'
    },
    'nord': {
        name: 'Nord',
        description: 'Arctic, north-bluish color palette',
        background: '#2e3440',
        foreground: '#d8dee9',
        cursor: '#d8dee9',
        selection: 'rgba(67, 76, 94, 0.5)',
        black: '#3b4252',
        red: '#bf616a',
        green: '#a3be8c',
        yellow: '#ebcb8b',
        blue: '#81a1c1',
        magenta: '#b48ead',
        cyan: '#88c0d0',
        white: '#e5e9f0',
        brightBlack: '#4c566a',
        brightRed: '#bf616a',
        brightGreen: '#a3be8c',
        brightYellow: '#ebcb8b',
        brightBlue: '#81a1c1',
        brightMagenta: '#b48ead',
        brightCyan: '#8fbcbb',
        brightWhite: '#eceff4'
    }
};

export default TERMINAL_THEMES;
